# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name:  website Deploy
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: 'Checkout Github Action' 
        uses: actions/checkout@master
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUDWAYS_METADEV_IP }}
          username: ${{ secrets.CLOUDWAYS_METADEV_USER }}
          key: ${{ secrets.TEST_CW_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            whoami
            ls -al



