# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          cloudways_username: ${{ secrets.CLOUDWAYS_METADEV_USER }}
          cloudways_server: ${{ secrets.CLOUDWAYS_METADEV_IP }}
          cloudways_deploy_path: '~/public_html/wp-content/themes/test-theme'
          cloudways_ssh_private_key: ${{ secrets.TEST_CW_SSH_PRIVATE_KEY }}
          build_script: node -v; \
            composer --version; \
            npm --version"
            #build_script: "npm install && composer install --no-dev --no-scripts"
